#!/usr/bin/env bash

for FILE in $(find . \( -name .git -type d \) -prune -o \( -type f \)); do
  if jq empty "$FILE" >/dev/null 2>&1; then
    TMP_FILE=$(mktemp)
    echo "Formatting JSON: $FILE"

    if jq . "$FILE" > "$TMP_FILE"; then
      mv "$TMP_FILE" "$FILE" && echo "Successfully formatted: $FILE"
    else 
      echo "ERROR: Failed to format $FILE, original untouched."
      rm -f "$TMP_FILE"
    fi
  else
    echo "Skipping (not JSON or unreadable): $FILE";
  fi
done
